-- AlterEnum
ALTER TYPE "InternalNotificationType" ADD VALUE IF NOT EXISTS 'NEW_PAYMENT_PROOF';
ALTER TYPE "InternalNotificationType" ADD VALUE IF NOT EXISTS 'CONFIRMED_PAYMENT_PROOF';
ALTER TYPE "InternalNotificationType" ADD VALUE IF NOT EXISTS 'CANCEL_PAYMENT_PROOF';

