export enum DomainErrorCode {
  VALIDATION = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  CONFLICT = 'CONFLICT',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_STATE = 'INVALID_STATE',
  BUSINESS_RULE = 'BUSINESS_RULE',
  UNKNOWN = 'UNKNOWN',
}
