-- AlterEnum: add new admin action log values
ALTER TYPE "UserActionLogAction" ADD VALUE 'ADMIN_UNSET_USER_VIP';
ALTER TYPE "UserActionLogAction" ADD VALUE 'ADMIN_BLOCK_USER';
ALTER TYPE "UserActionLogAction" ADD VALUE 'ADMIN_UNBLOCK_USER';
ALTER TYPE "UserActionLogAction" ADD VALUE 'ADMIN_UPDATE_SYSTEM_SETTING';
ALTER TYPE "UserActionLogAction" ADD VALUE 'ADMIN_CREATE_EXCHANGE_RATE';
ALTER TYPE "UserActionLogAction" ADD VALUE 'ADMIN_UPDATE_EXCHANGE_RATE';
ALTER TYPE "UserActionLogAction" ADD VALUE 'ADMIN_DELETE_EXCHANGE_RATE';
ALTER TYPE "UserActionLogAction" ADD VALUE 'ADMIN_CREATE_CURRENCY';
ALTER TYPE "UserActionLogAction" ADD VALUE 'ADMIN_UPDATE_CURRENCY';
ALTER TYPE "UserActionLogAction" ADD VALUE 'ADMIN_DELETE_CURRENCY';
